// GEN-ASSET: Asset Registry — scans assets/ for qforge JSON manifests.
//
// Original Phase 4:
//   • Loads `AssetManifest` sidecars generated by asset-forge (qforge generate)
//   • Provides `AssetRegistry` resource for the rack UI asset browser
//   • Socket matching logic: PASSAGE_MD ↔ PASSAGE_MD, OPEN ↔ any, None ↔ None
//   • `RoomChain`: procedural room chaining from a seed integer

use bevy::prelude::*;
use serde::Deserialize;
use std::{
    collections::HashSet,
    path::{Path, PathBuf},
};
use tracing::{info, warn};

// ── Manifest types (mirrors asset-forge/src/manifest.rs) ─────────────────────
// Defined here because asset-forge is a [[bin]] crate and cannot be depended on.

#[derive(Debug, Clone, Deserialize)]
pub struct QforgeManifest {
    pub id:     String,
    pub name:   String,
    pub stem:   String,
    pub domain: String,          // "arch" | "bio" | "mech" | "char" | "prop"
    #[serde(default)]
    pub zone:     Option<String>,
    #[serde(default)]
    pub function: Option<String>,
    #[serde(default)]
    pub variant:  Option<String>,
    #[serde(default)]
    pub tags:     Vec<String>,
    #[serde(default)]
    pub grid:     Option<[u32; 2]>,
    pub sockets:  Option<QforgeSockets>,
    pub files:    Option<QforgeFileRefs>,
    #[serde(default)]
    pub quantum_module: Option<String>,
    #[serde(default)]
    pub resonance_hz:   Option<f64>,
}

#[derive(Debug, Clone, Deserialize, Default)]
pub struct QforgeSockets {
    pub north: Option<String>,
    pub south: Option<String>,
    pub east:  Option<String>,
    pub west:  Option<String>,
    pub up:    Option<String>,
    pub down:  Option<String>,
}

#[derive(Debug, Clone, Deserialize, Default)]
pub struct QforgeFileRefs {
    pub gltf:      Option<String>,
    pub sprite:    Option<String>,
    pub normal:    Option<String>,
    pub thumbnail: Option<String>,
}

// ── AssetEntry — a loaded manifest with resolved paths ───────────────────────

#[derive(Debug, Clone)]
pub struct AssetEntry {
    pub manifest: QforgeManifest,
    /// Absolute path to the `assets/` root (for resolving relative file refs)
    pub root:     PathBuf,
}

impl AssetEntry {
    /// Resolved absolute path to the GLTF file, or None if it doesn't exist.
    pub fn gltf_abs_path(&self) -> Option<PathBuf> {
        let rel = self.manifest.files.as_ref()?.gltf.as_deref()?;
        let abs = self.root.join(rel);
        if abs.exists() { Some(abs) } else { None }
    }

    /// Path relative to the Bevy `assets/` directory (for asset server loading).
    pub fn gltf_bevy_path(&self) -> Option<String> {
        self.manifest.files.as_ref()?.gltf.clone()
    }

    pub fn domain(&self) -> &str { &self.manifest.domain }
    pub fn zone(&self)   -> Option<&str> { self.manifest.zone.as_deref() }

    /// Grid footprint in world units (1 unit = 1 tile cell).
    pub fn grid(&self) -> [u32; 2] {
        self.manifest.grid.unwrap_or([1, 1])
    }
}

// ── Socket matching ───────────────────────────────────────────────────────────

/// Directions from which tiles connect to one another.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TileDir { North, South, East, West }

impl TileDir {
    pub fn offset(&self, pos: (i32, i32)) -> (i32, i32) {
        match self {
            Self::North => (pos.0,     pos.1 + 1),
            Self::South => (pos.0,     pos.1 - 1),
            Self::East  => (pos.0 + 1, pos.1    ),
            Self::West  => (pos.0 - 1, pos.1    ),
        }
    }

    pub fn opposite(&self) -> Self {
        match self {
            Self::North => Self::South,
            Self::South => Self::North,
            Self::East  => Self::West,
            Self::West  => Self::East,
        }
    }
}

/// Two socket labels are compatible when:
/// - Both are None   (solid wall ↔ solid wall)
/// - Either is "OPEN" (wildcard passage)
/// - Both are Some(s) and `s` is identical
pub fn sockets_compatible(a: Option<&str>, b: Option<&str>) -> bool {
    match (a, b) {
        (None, None)         => true,
        (Some("OPEN"), _)
        | (_, Some("OPEN")) => true,
        (Some(a), Some(b))  => a == b,
        _                    => false,
    }
}

/// Check whether two manifests can be placed adjacent in `dir` from `tile_a`.
pub fn tiles_compatible(tile_a: &QforgeManifest, tile_b: &QforgeManifest, dir: TileDir) -> bool {
    let sa = tile_a.sockets.as_ref();
    let sb = tile_b.sockets.as_ref();

    let (sock_a, sock_b) = match dir {
        TileDir::North => (sa.and_then(|s| s.north.as_deref()), sb.and_then(|s| s.south.as_deref())),
        TileDir::South => (sa.and_then(|s| s.south.as_deref()), sb.and_then(|s| s.north.as_deref())),
        TileDir::East  => (sa.and_then(|s| s.east.as_deref()),  sb.and_then(|s| s.west.as_deref())),
        TileDir::West  => (sa.and_then(|s| s.west.as_deref()),  sb.and_then(|s| s.east.as_deref())),
    };

    sockets_compatible(sock_a, sock_b)
}

// ── AssetRegistry resource ────────────────────────────────────────────────────

#[derive(Resource, Default)]
pub struct AssetRegistry {
    pub entries: Vec<AssetEntry>,
}

impl AssetRegistry {
    /// Scan the given directory (and its subdirectories) for qforge manifest JSON files.
    /// Files that can't be parsed as `QforgeManifest` are silently skipped.
    pub fn load_from(assets_root: impl AsRef<Path>) -> Self {
        let root = assets_root.as_ref();
        let mut entries = Vec::new();
        scan_dir(root, root, &mut entries);
        info!(count = entries.len(), dir = %root.display(), "Asset manifests scanned");
        Self { entries }
    }

    pub fn by_domain<'a>(&'a self, domain: &'a str) -> impl Iterator<Item = &'a AssetEntry> {
        self.entries.iter().filter(move |e| e.manifest.domain == domain)
    }

    pub fn by_zone<'a>(&'a self, zone: &'a str) -> impl Iterator<Item = &'a AssetEntry> {
        self.entries.iter().filter(move |e| e.zone() == Some(zone))
    }

    pub fn total(&self) -> usize { self.entries.len() }
    pub fn gltf_count(&self) -> usize {
        self.entries.iter().filter(|e| e.gltf_abs_path().is_some()).count()
    }
}

fn scan_dir(dir: &Path, root: &Path, out: &mut Vec<AssetEntry>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return; };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            scan_dir(&path, root, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("json") {
            match std::fs::read_to_string(&path) {
                Ok(text) => {
                    // Attempt parse; skip silently if not a QforgeManifest
                    if let Ok(manifest) = serde_json::from_str::<QforgeManifest>(&text) {
                        out.push(AssetEntry { manifest, root: root.to_path_buf() });
                    }
                }
                Err(e) => warn!(path = %path.display(), error = %e, "Failed to read asset JSON"),
            }
        }
    }
}

// ── AssetToken ECS component ──────────────────────────────────────────────────

/// Attached to every entity that was spawned from a qforge manifest.
/// Allows ECS queries like `Query<&Transform, With<AssetToken>>`.
#[derive(Component, Debug, Clone)]
pub struct AssetToken {
    pub manifest_id: String,
    pub domain:      String,
    pub stem:        String,
    pub grid:        [u32; 2],
}

// ── PlacedTile — result of room chaining ─────────────────────────────────────

#[derive(Component, Debug, Clone)]
pub struct PlacedTile {
    /// Grid cell position (X, Z in tile units)
    pub grid_x:      i32,
    pub grid_z:      i32,
    /// Index into `AssetRegistry::entries` (for looking up the manifest)
    pub entry_index: usize,
}

// ── RoomChain resource ────────────────────────────────────────────────────────

#[derive(Resource)]
pub struct RoomChain {
    pub seed:       u64,
    pub room_count: usize,
}

impl Default for RoomChain {
    fn default() -> Self {
        Self { seed: 0xdeadbeef_cafe_1234, room_count: 6 }
    }
}

// ── Asset registry plugin ─────────────────────────────────────────────────────

pub struct AssetRegistryPlugin;

impl Plugin for AssetRegistryPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<RoomChain>()
            .add_systems(Startup, spawn_room_chain);
    }
}

// ── Room chain spawner ────────────────────────────────────────────────────────

/// Procedurally chain rooms from the RoomChain seed.
/// When GLTFs exist, loads them via AssetServer.
/// Until then, spawns colour-coded placeholder cubes with socket markers.
pub fn spawn_room_chain(
    mut commands:  Commands,
    registry:      Res<AssetRegistry>,
    chain_cfg:     Res<RoomChain>,
    mut meshes:    ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    if registry.entries.is_empty() {
        info!("No asset manifests found — skipping room chain generation");
        return;
    }

    let placed = build_chain(&registry, chain_cfg.seed, chain_cfg.room_count);

    for (grid_pos, entry_idx) in &placed {
        let entry = &registry.entries[*entry_idx];
        let [gw, _gd] = entry.grid();
        let world_x  = grid_pos.0 as f32 * (gw as f32 * 4.0 + 2.0);
        let world_z  = grid_pos.1 as f32 * (gw as f32 * 4.0 + 2.0);

        // Colour from domain
        let base_col = domain_color(entry.domain());
        let token = AssetToken {
            manifest_id: entry.manifest.id.clone(),
            domain:      entry.manifest.domain.clone(),
            stem:        entry.manifest.stem.clone(),
            grid:        entry.grid(),
        };

        if let Some(gltf_path) = entry.gltf_bevy_path() {
            // GLTF exists on disk — spawn a placeholder marker and note the path.
            // Full SceneBundle loading happens in the SceneSpawner; for now mark as pending.
            commands.spawn((
                SpatialBundle {
                    transform: Transform::from_xyz(world_x, 0.0, world_z),
                    ..Default::default()
                },
                token,
                PlacedTile { grid_x: grid_pos.0, grid_z: grid_pos.1, entry_index: *entry_idx },
                Name::new(entry.manifest.name.clone()),
            ));
            info!(stem = %entry.manifest.stem, gltf = %gltf_path, "Tile has GLTF — queued for scene load");
        } else {
            // No GLTF yet — spawn a coloured diagnostic box
            let tile_w = gw as f32 * 4.0;
            let mesh = meshes.add(Cuboid::new(tile_w, 0.5, tile_w));
            let mat  = materials.add(StandardMaterial {
                base_color:           Color::srgba(base_col[0], base_col[1], base_col[2], 0.85),
                perceptual_roughness: 0.8,
                metallic:             0.1,
                ..Default::default()
            });

            commands.spawn((
                PbrBundle {
                    mesh,
                    material: mat,
                    transform: Transform::from_xyz(world_x, 0.25, world_z),
                    ..Default::default()
                },
                token,
                PlacedTile { grid_x: grid_pos.0, grid_z: grid_pos.1, entry_index: *entry_idx },
                Name::new(entry.manifest.name.clone()),
            ));
        }
    }

    info!(rooms = placed.len(), seed = chain_cfg.seed, "Room chain generated");
}

// ── Procedural room chaining algorithm ───────────────────────────────────────

fn build_chain(
    registry: &AssetRegistry,
    seed:     u64,
    count:    usize,
) -> Vec<((i32, i32), usize)> {
    let n = registry.entries.len();
    if n == 0 { return Vec::new(); }

    let mut rng      = seed;
    let mut placed   = Vec::<((i32, i32), usize)>::new();
    let mut occupied = HashSet::<(i32, i32)>::new();

    // First room at origin
    let first = rng_pick(&mut rng, n);
    placed.push(((0, 0), first));
    occupied.insert((0, 0));

    let dirs = [TileDir::North, TileDir::South, TileDir::East, TileDir::West];

    'outer: for _ in 1..count {
        // Pick a random already-placed room to expand from
        let src_i = rng_pick(&mut rng, placed.len());
        let (src_grid, src_entry_idx) = placed[src_i];
        let src_manifest = &registry.entries[src_entry_idx].manifest;

        // Try directions in a seed-derived order
        let dir_start = rng_pick(&mut rng, 4);
        for di in 0..4 {
            let dir      = dirs[(dir_start + di) % 4];
            let next_pos = dir.offset(src_grid);
            if occupied.contains(&next_pos) { continue; }

            // Find compatible tiles
            let candidates: Vec<usize> = (0..n)
                .filter(|&i| tiles_compatible(src_manifest, &registry.entries[i].manifest, dir))
                .collect();

            let pick = if candidates.is_empty() {
                // Socket constraint not yet satisfiable (no assets) — use any tile
                rng_pick(&mut rng, n)
            } else {
                candidates[rng_pick(&mut rng, candidates.len())]
            };

            placed.push((next_pos, pick));
            occupied.insert(next_pos);
            continue 'outer;
        }
    }

    placed
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn rng_pick(s: &mut u64, n: usize) -> usize {
    *s = s.wrapping_mul(6_364_136_223_846_793_005)
          .wrapping_add(1_442_695_040_888_963_407);
    ((*s >> 33) as usize) % n
}

fn domain_color(domain: &str) -> [f32; 3] {
    match domain {
        "arch" => [0.12, 0.28, 0.55],
        "bio"  => [0.15, 0.55, 0.22],
        "mech" => [0.55, 0.35, 0.12],
        "char" => [0.55, 0.15, 0.45],
        _      => [0.35, 0.35, 0.35],
    }
}
