(
    name: "GLTFShader",

    resources: [
        (
            name: "diffuseTexture",
            kind: Texture(kind: Sampler2D, fallback: White),
            binding: 0
        ),
        (
            name: "normalTexture",
            kind: Texture(kind: Sampler2D, fallback: Normal),
            binding: 1
        ),
        (
            name: "metallicRoughnessTexture",
            kind: Texture(kind: Sampler2D, fallback: White),
            binding: 2
        ),
        (
            name: "heightTexture",
            kind: Texture(kind: Sampler2D, fallback: Black),
            binding: 3
        ),
        (
            name: "emissionTexture",
            kind: Texture(kind: Sampler2D, fallback: White),
            binding: 4
        ),
        (
            name: "lightmapTexture",
            kind: Texture(kind: Sampler2D, fallback: Black),
            binding: 5
        ),
        (
            name: "aoTexture",
            kind: Texture(kind: Sampler2D, fallback: White),
            binding: 6
        ),
        (
            name: "blendShapesStorage",
            kind: Texture(kind: Sampler3D, fallback: Volume),
            binding: 7
        ),
        (
            name: "properties",
            kind: PropertyGroup([
                (
                    name: "texCoordScale",
                    kind: Vector2(value: (1.0, 1.0)),
                ),
                (
                    name: "layerIndex",
                    kind: UInt(value: 0),
                ),
                (
                    name: "emissionStrength",
                    kind: Vector3(value: (2.0, 2.0, 2.0)),
                ),
                (
                    name: "diffuseColor",
                    kind: Color(r: 255, g: 255, b: 255, a: 255),
                ),
                (
                    name: "parallaxCenter",
                    kind: Float(value: 0.0),
                ),
                (
                    name: "parallaxScale",
                    kind: Float(value: 0.08),
                ),
                (
                    name: "metallicFactor",
                    kind: Float(value: 1.0)
                ),
                (
                    name: "roughnessFactor",
                    kind: Float(value: 1.0)
                )
            ]),
            binding: 0
        ),
        (
            name: "fyrox_instanceData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 1
        ),
        (
            name: "fyrox_boneMatrices",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 2
        ),
        (
            name: "fyrox_graphicsSettings",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 3
        ),
        (
            name: "fyrox_cameraData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 4
        ),
        (
            name: "fyrox_lightData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 5
        ),
    ],

    passes: [
        (
            name: "GBuffer",
            draw_parameters: DrawParameters(
                cull_face: Some(Back),
                color_write: ColorMask(
                    red: true,
                    green: true,
                    blue: true,
                    alpha: true,
                ),
                depth_write: true,
                stencil_test: None,
                depth_test: Some(Less),
                blend: None,
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Keep,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),
            vertex_shader:
                r#"
                struct VertexInput {
                    @builtin(vertex_index) vertex_index: u32,
                    @location(0) vertexPosition: vec3f,
                    @location(1) vertexTexCoord: vec2f,
                    @location(2) vertexNormal: vec3f,
                    @location(3) vertexTangent: vec4f,
                    @location(4) boneWeights: vec4f,
                    @location(5) boneIndices: vec4f,
                    @location(6) vertexSecondTexCoord: vec2f,
                };

                struct VertexOutput {
                    @builtin(position) position: vec4f,
                    @location(0) outPosition: vec3f,
                    @location(1) normal: vec3f,
                    @location(2) texCoord: vec2f,
                    @location(3) tangent: vec3f,
                    @location(4) binormal: vec3f,
                    @location(5) secondTexCoord: vec2f,
                };

                @vertex
                fn vs_main(input: VertexInput) -> VertexOutput {
                    var output: VertexOutput;

                    var localPosition = vec4f(0.0);
                    var localNormal = vec3f(0.0);
                    var localTangent = vec3f(0.0);

                    var inputPosition = vec4f(input.vertexPosition, 1.0);
                    var inputNormal = input.vertexNormal;
                    var inputTangent = input.vertexTangent.xyz;

                    for (var i: i32 = 0; i < fyrox_instanceData.blendShapesCount; i++) {
                        var offsets = S_FetchBlendShapeOffsets(blendShapesStorage_tex, blendShapesStorage_samp, i32(input.vertex_index), i);
                        var weight = fyrox_instanceData.blendShapesWeights[i / 4][i % 4];
                        inputPosition = vec4f(inputPosition.xyz + offsets.position * weight, inputPosition.w);
                        inputNormal += offsets.normal * weight;
                        inputTangent += offsets.tangent * weight;
                    }

                    if (fyrox_instanceData.useSkeletalAnimation != 0u)
                    {
                        var i0 = i32(input.boneIndices.x);
                        var i1 = i32(input.boneIndices.y);
                        var i2 = i32(input.boneIndices.z);
                        var i3 = i32(input.boneIndices.w);

                        var m0 = fyrox_boneMatrices.matrices[i0];
                        var m1 = fyrox_boneMatrices.matrices[i1];
                        var m2 = fyrox_boneMatrices.matrices[i2];
                        var m3 = fyrox_boneMatrices.matrices[i3];

                        localPosition += m0 * inputPosition * input.boneWeights.x;
                        localPosition += m1 * inputPosition * input.boneWeights.y;
                        localPosition += m2 * inputPosition * input.boneWeights.z;
                        localPosition += m3 * inputPosition * input.boneWeights.w;

                        localNormal += mat3x3f(m0[0].xyz, m0[1].xyz, m0[2].xyz) * inputNormal * input.boneWeights.x;
                        localNormal += mat3x3f(m1[0].xyz, m1[1].xyz, m1[2].xyz) * inputNormal * input.boneWeights.y;
                        localNormal += mat3x3f(m2[0].xyz, m2[1].xyz, m2[2].xyz) * inputNormal * input.boneWeights.z;
                        localNormal += mat3x3f(m3[0].xyz, m3[1].xyz, m3[2].xyz) * inputNormal * input.boneWeights.w;

                        localTangent += mat3x3f(m0[0].xyz, m0[1].xyz, m0[2].xyz) * inputTangent * input.boneWeights.x;
                        localTangent += mat3x3f(m1[0].xyz, m1[1].xyz, m1[2].xyz) * inputTangent * input.boneWeights.y;
                        localTangent += mat3x3f(m2[0].xyz, m2[1].xyz, m2[2].xyz) * inputTangent * input.boneWeights.z;
                        localTangent += mat3x3f(m3[0].xyz, m3[1].xyz, m3[2].xyz) * inputTangent * input.boneWeights.w;
                    }
                    else
                    {
                        localPosition = inputPosition;
                        localNormal = inputNormal;
                        localTangent = inputTangent;
                    }

                    var nm = mat3x3f(fyrox_instanceData.worldMatrix[0].xyz, fyrox_instanceData.worldMatrix[1].xyz, fyrox_instanceData.worldMatrix[2].xyz);
                    output.normal = normalize(nm * localNormal);
                    output.tangent = normalize(nm * localTangent);
                    output.binormal = normalize(input.vertexTangent.w * cross(output.normal, output.tangent));
                    output.texCoord = input.vertexTexCoord;
                    output.outPosition = (fyrox_instanceData.worldMatrix * localPosition).xyz;
                    output.secondTexCoord = input.vertexSecondTexCoord;

                    output.position = fyrox_instanceData.worldViewProjection * localPosition;
                    return output;
                }
                "#,
            fragment_shader:
                r#"
                struct GBufferOutput {
                    @location(0) outColor: vec4f,
                    @location(1) outNormal: vec4f,
                    @location(2) outAmbient: vec4f,
                    @location(3) outMaterial: vec4f,
                    @location(4) outDecalMask: u32,
                };

                @fragment
                fn fs_main(
                    @location(0) position: vec3f,
                    @location(1) normal: vec3f,
                    @location(2) texCoord: vec2f,
                    @location(3) tangent: vec3f,
                    @location(4) binormal: vec3f,
                    @location(5) secondTexCoord: vec2f
                ) -> GBufferOutput {
                    var tangentSpace = mat3x3f(tangent, binormal, normal);
                    var toFragment = normalize(position - fyrox_cameraData.position);

                    var tc: vec2f;
                    if (fyrox_graphicsSettings.usePOM != 0u) {
                        var toFragmentTangentSpace = normalize(transpose(tangentSpace) * toFragment);
                        tc = S_ComputeParallaxTextureCoordinates(
                            heightTexture_tex,
                            heightTexture_samp,
                            toFragmentTangentSpace,
                            texCoord * properties.texCoordScale,
                            properties.parallaxCenter,
                            properties.parallaxScale
                        );
                    } else {
                        tc = texCoord * properties.texCoordScale;
                    }

                    var output: GBufferOutput;
                    output.outColor = properties.diffuseColor * textureSample(diffuseTexture_tex, diffuseTexture_samp, tc);

                    // Alpha test.
                    if (output.outColor.a < 0.5) {
                        discard;
                    }
                    output.outColor.a = 1.0;

                    var n = normalize(textureSample(normalTexture_tex, normalTexture_samp, tc) * 2.0 - 1.0);
                    output.outNormal = vec4f(normalize(tangentSpace * n.xyz) * 0.5 + 0.5, 1.0);

                    output.outMaterial.x = properties.metallicFactor * textureSample(metallicRoughnessTexture_tex, metallicRoughnessTexture_samp, tc).b; // Metallic
                    output.outMaterial.y = properties.roughnessFactor * textureSample(metallicRoughnessTexture_tex, metallicRoughnessTexture_samp, tc).g; // Roughness
                    output.outMaterial.z = textureSample(aoTexture_tex, aoTexture_samp, tc).r;
                    output.outMaterial.a = 1.0;

                    output.outAmbient = vec4f(properties.emissionStrength * textureSample(emissionTexture_tex, emissionTexture_samp, tc).rgb + textureSample(lightmapTexture_tex, lightmapTexture_samp, secondTexCoord).rgb, 1.0);

                    output.outDecalMask = properties.layerIndex;

                    return output;
                }
                "#,
        ),
        (
            name: "Forward",
            draw_parameters: DrawParameters(
                cull_face: Some(Back),
                color_write: ColorMask(
                    red: true,
                    green: true,
                    blue: true,
                    alpha: true,
                ),
                depth_write: true,
                stencil_test: None,
                depth_test: Some(Less),
                blend: Some(BlendParameters(
                    func: BlendFunc(
                        sfactor: SrcAlpha,
                        dfactor: OneMinusSrcAlpha,
                        alpha_sfactor: SrcAlpha,
                        alpha_dfactor: OneMinusSrcAlpha,
                    ),
                    equation: BlendEquation(
                        rgb: Add,
                        alpha: Add
                    )
                )),
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Keep,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),
            vertex_shader:
               r#"
                struct VertexInput {
                    @builtin(vertex_index) vertex_index: u32,
                    @location(0) vertexPosition: vec3f,
                    @location(1) vertexTexCoord: vec2f,
                    @location(2) vertexNormal: vec3f,
                    @location(3) vertexTangent: vec4f,
                    @location(4) boneWeights: vec4f,
                    @location(5) boneIndices: vec4f,
                    @location(6) vertexSecondTexCoord: vec2f,
                };

                struct VertexOutput {
                    @builtin(position) position: vec4f,
                    @location(0) outPosition: vec3f,
                    @location(1) texCoord: vec2f,
                };

                @vertex
                fn vs_main(input: VertexInput) -> VertexOutput {
                    var output: VertexOutput;

                    var localPosition = vec4f(0.0);

                    var inputPosition = vec4f(input.vertexPosition, 1.0);

                    for (var i: i32 = 0; i < fyrox_instanceData.blendShapesCount; i++) {
                        var offsets = S_FetchBlendShapeOffsets(blendShapesStorage_tex, blendShapesStorage_samp, i32(input.vertex_index), i);
                        var weight = fyrox_instanceData.blendShapesWeights[i / 4][i % 4];
                        inputPosition = vec4f(inputPosition.xyz + offsets.position * weight, inputPosition.w);
                    }

                    if (fyrox_instanceData.useSkeletalAnimation != 0u)
                    {
                        var i0 = i32(input.boneIndices.x);
                        var i1 = i32(input.boneIndices.y);
                        var i2 = i32(input.boneIndices.z);
                        var i3 = i32(input.boneIndices.w);

                        var m0 = fyrox_boneMatrices.matrices[i0];
                        var m1 = fyrox_boneMatrices.matrices[i1];
                        var m2 = fyrox_boneMatrices.matrices[i2];
                        var m3 = fyrox_boneMatrices.matrices[i3];

                        localPosition += m0 * inputPosition * input.boneWeights.x;
                        localPosition += m1 * inputPosition * input.boneWeights.y;
                        localPosition += m2 * inputPosition * input.boneWeights.z;
                        localPosition += m3 * inputPosition * input.boneWeights.w;
                    }
                    else
                    {
                        localPosition = inputPosition;
                    }
                    output.position = fyrox_instanceData.worldViewProjection * localPosition;
                    output.texCoord = input.vertexTexCoord;
                    output.outPosition = (fyrox_instanceData.worldMatrix * localPosition).xyz;
                    return output;
                }
               "#,

           fragment_shader:
               r#"
                @fragment
                fn fs_main(@location(0) position: vec3f, @location(1) texCoord: vec2f) -> @location(0) vec4f {
                    return properties.diffuseColor * textureSample(diffuseTexture_tex, diffuseTexture_samp, texCoord);
                }
               "#,
        ),
        (
            name: "DirectionalShadow",

            draw_parameters: DrawParameters (
                cull_face: Some(Back),
                color_write: ColorMask(
                    red: false,
                    green: false,
                    blue: false,
                    alpha: false,
                ),
                depth_write: true,
                stencil_test: None,
                depth_test: Some(Less),
                blend: None,
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Keep,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),

            vertex_shader:
                r#"
                struct VertexInput {
                    @builtin(vertex_index) vertex_index: u32,
                    @location(0) vertexPosition: vec3f,
                    @location(1) vertexTexCoord: vec2f,
                    @location(2) vertexNormal: vec3f,
                    @location(3) vertexTangent: vec4f,
                    @location(4) boneWeights: vec4f,
                    @location(5) boneIndices: vec4f,
                    @location(6) vertexSecondTexCoord: vec2f,
                };

                struct VertexOutput {
                    @builtin(position) position: vec4f,
                    @location(0) texCoord: vec2f,
                };

                @vertex
                fn vs_main(input: VertexInput) -> VertexOutput {
                    var output: VertexOutput;

                    var localPosition = vec4f(0.0);

                    var inputPosition = vec4f(input.vertexPosition, 1.0);

                    for (var i: i32 = 0; i < fyrox_instanceData.blendShapesCount; i++) {
                        var offsets = S_FetchBlendShapeOffsets(blendShapesStorage_tex, blendShapesStorage_samp, i32(input.vertex_index), i);
                        var weight = fyrox_instanceData.blendShapesWeights[i / 4][i % 4];
                        inputPosition = vec4f(inputPosition.xyz + offsets.position * weight, inputPosition.w);
                    }

                    if (fyrox_instanceData.useSkeletalAnimation != 0u)
                    {
                        var vertex = vec4f(input.vertexPosition, 1.0);

                        var m0 = fyrox_boneMatrices.matrices[i32(input.boneIndices.x)];
                        var m1 = fyrox_boneMatrices.matrices[i32(input.boneIndices.y)];
                        var m2 = fyrox_boneMatrices.matrices[i32(input.boneIndices.z)];
                        var m3 = fyrox_boneMatrices.matrices[i32(input.boneIndices.w)];

                        localPosition += m0 * inputPosition * input.boneWeights.x;
                        localPosition += m1 * inputPosition * input.boneWeights.y;
                        localPosition += m2 * inputPosition * input.boneWeights.z;
                        localPosition += m3 * inputPosition * input.boneWeights.w;
                    }
                    else
                    {
                        localPosition = inputPosition;
                    }

                    output.position = fyrox_instanceData.worldViewProjection * localPosition;
                    output.texCoord = input.vertexTexCoord;
                    return output;
                }
                "#,

            fragment_shader:
                r#"
                @fragment
                fn fs_main(@location(0) texCoord: vec2f) {
                    if (textureSample(diffuseTexture_tex, diffuseTexture_samp, texCoord).a < 0.2) { discard; }
                }
                "#,
        ),
        (
            name: "SpotShadow",

            draw_parameters: DrawParameters (
                cull_face: Some(Back),
                color_write: ColorMask(
                    red: false,
                    green: false,
                    blue: false,
                    alpha: false,
                ),
                depth_write: true,
                stencil_test: None,
                depth_test: Some(Less),
                blend: None,
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Keep,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),

            vertex_shader:
                r#"
                struct VertexInput {
                    @builtin(vertex_index) vertex_index: u32,
                    @location(0) vertexPosition: vec3f,
                    @location(1) vertexTexCoord: vec2f,
                    @location(2) vertexNormal: vec3f,
                    @location(3) vertexTangent: vec4f,
                    @location(4) boneWeights: vec4f,
                    @location(5) boneIndices: vec4f,
                    @location(6) vertexSecondTexCoord: vec2f,
                };

                struct VertexOutput {
                    @builtin(position) position: vec4f,
                    @location(0) texCoord: vec2f,
                };

                @vertex
                fn vs_main(input: VertexInput) -> VertexOutput {
                    var output: VertexOutput;

                    var localPosition = vec4f(0.0);

                    var inputPosition = vec4f(input.vertexPosition, 1.0);

                    for (var i: i32 = 0; i < fyrox_instanceData.blendShapesCount; i++) {
                        var offsets = S_FetchBlendShapeOffsets(blendShapesStorage_tex, blendShapesStorage_samp, i32(input.vertex_index), i);
                        var weight = fyrox_instanceData.blendShapesWeights[i / 4][i % 4];
                        inputPosition = vec4f(inputPosition.xyz + offsets.position * weight, inputPosition.w);
                    }

                    if (fyrox_instanceData.useSkeletalAnimation != 0u)
                    {
                        var vertex = vec4f(input.vertexPosition, 1.0);

                        var m0 = fyrox_boneMatrices.matrices[i32(input.boneIndices.x)];
                        var m1 = fyrox_boneMatrices.matrices[i32(input.boneIndices.y)];
                        var m2 = fyrox_boneMatrices.matrices[i32(input.boneIndices.z)];
                        var m3 = fyrox_boneMatrices.matrices[i32(input.boneIndices.w)];

                        localPosition += m0 * inputPosition * input.boneWeights.x;
                        localPosition += m1 * inputPosition * input.boneWeights.y;
                        localPosition += m2 * inputPosition * input.boneWeights.z;
                        localPosition += m3 * inputPosition * input.boneWeights.w;
                    }
                    else
                    {
                        localPosition = inputPosition;
                    }

                    output.position = fyrox_instanceData.worldViewProjection * localPosition;
                    output.texCoord = input.vertexTexCoord;
                    return output;
                }
                "#,

            fragment_shader:
                r#"
                @fragment
                fn fs_main(@location(0) texCoord: vec2f) {
                    if (textureSample(diffuseTexture_tex, diffuseTexture_samp, texCoord).a < 0.2) { discard; }
                }
                "#,
        ),
        (
            name: "PointShadow",

            draw_parameters: DrawParameters (
                cull_face: Some(Back),
                color_write: ColorMask(
                    red: true,
                    green: true,
                    blue: true,
                    alpha: true,
                ),
                depth_write: true,
                stencil_test: None,
                depth_test: Some(Less),
                blend: None,
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Keep,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),

            vertex_shader:
                r#"
                struct VertexInput {
                    @builtin(vertex_index) vertex_index: u32,
                    @location(0) vertexPosition: vec3f,
                    @location(1) vertexTexCoord: vec2f,
                    @location(2) vertexNormal: vec3f,
                    @location(3) vertexTangent: vec4f,
                    @location(4) boneWeights: vec4f,
                    @location(5) boneIndices: vec4f,
                    @location(6) vertexSecondTexCoord: vec2f,
                };

                struct VertexOutput {
                    @builtin(position) position: vec4f,
                    @location(0) texCoord: vec2f,
                    @location(1) worldPosition: vec3f,
                };

                @vertex
                fn vs_main(input: VertexInput) -> VertexOutput {
                    var output: VertexOutput;

                    var localPosition = vec4f(0.0);

                    var inputPosition = vec4f(input.vertexPosition, 1.0);

                    for (var i: i32 = 0; i < fyrox_instanceData.blendShapesCount; i++) {
                        var offsets = S_FetchBlendShapeOffsets(blendShapesStorage_tex, blendShapesStorage_samp, i32(input.vertex_index), i);
                        var weight = fyrox_instanceData.blendShapesWeights[i / 4][i % 4];
                        inputPosition = vec4f(inputPosition.xyz + offsets.position * weight, inputPosition.w);
                    }

                    if (fyrox_instanceData.useSkeletalAnimation != 0u)
                    {
                        var vertex = vec4f(input.vertexPosition, 1.0);

                        var m0 = fyrox_boneMatrices.matrices[i32(input.boneIndices.x)];
                        var m1 = fyrox_boneMatrices.matrices[i32(input.boneIndices.y)];
                        var m2 = fyrox_boneMatrices.matrices[i32(input.boneIndices.z)];
                        var m3 = fyrox_boneMatrices.matrices[i32(input.boneIndices.w)];

                        localPosition += m0 * inputPosition * input.boneWeights.x;
                        localPosition += m1 * inputPosition * input.boneWeights.y;
                        localPosition += m2 * inputPosition * input.boneWeights.z;
                        localPosition += m3 * inputPosition * input.boneWeights.w;
                    }
                    else
                    {
                        localPosition = inputPosition;
                    }

                    output.position = fyrox_instanceData.worldViewProjection * localPosition;
                    output.worldPosition = (fyrox_instanceData.worldMatrix * localPosition).xyz;
                    output.texCoord = input.vertexTexCoord;
                    return output;
                }
                "#,

            fragment_shader:
                r#"
                struct PointShadowOutput {
                    @location(0) depth: f32,
                };

                @fragment
                fn fs_main(@location(0) texCoord: vec2f, @location(1) worldPosition: vec3f) -> PointShadowOutput {
                    if (textureSample(diffuseTexture_tex, diffuseTexture_samp, texCoord).a < 0.2) { discard; }
                    var output: PointShadowOutput;
                    output.depth = length(fyrox_lightData.lightPosition - worldPosition);
                    return output;
                }
                "#,
        )
    ],
)
