name: Feature request
description: This is for requesting features or optimisations.
body:
- type: input
  attributes:
    label: What feature do you want to have you included?
    placeholder: E.g New widget, framework feature...
  validations:
    required: true
- type: checkboxes
  attributes:
    label: What part of RG3D does this feature apply to?
    options:
      - label: sound
      - label: animation
      - label: physics
      - label: user-interface
      - label: graphics
      - label: docs
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional details
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Are you willing to contribute to its development?
    options:
      - label: Yes I am
        required: true
      - label: No I am not
