name: Feature request
description: This is for requesting features or optimisations.
body:
- type: input
  attributes:
    label: What feature do you want to have you included?
    placeholder: E.g New widget, framework feature...
- type: checkboxes
  attributes:
    label: What part of RG3D does this feature apply to?
    options:
      - label: sound
      - label: animation
      - label: physics
      - label: user-interface
      - label: graphics
- type: textarea
  attributes:
    label: Additional features
  validations:
    required: true
