[package]
name = "rg3d-sound"
version = "0.25.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2021"
license = "MIT"
description = "Sound library for games."
keywords = ["sound", "game", "hrtf", "binaural", "reverb"]
categories = ["game-development", "multimedia::audio"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md", "/examples/*"]
homepage = "https://rg3d.rs"
documentation = "https://docs.rs/rg3d-sound"
repository = "https://github.com/mrDIMAS/rg3d"
readme = "README.md"
resolver = "2"
rust-version = "1.56"

[dependencies]
rg3d-core = { path = "../rg3d-core", version = "0.18.0" }
rg3d-resource = { path = "../rg3d-resource", version = "0.2.0" }
lewton = "0.10.2"
hrtf = "0.7.0"
hound = "3.4.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = {version = "0.3.9", features = ["minwindef", "winnt", "windef", "winuser", "dsound", "synchapi", "winbase" ] }

[target.'cfg(target_os = "linux")'.dependencies]
alsa-sys = { version = "0.3.1" }

[target.'cfg(target_os = "macos")'.dependencies]
coreaudio-sys = { version = "0.2.8" }
core-foundation-sys = { version = "0.8.2" }

[features]
enable_profiler = ["rg3d-core/enable_profiler"]
