(
    name: "StandardSpriteShader",

    resources: [
        (
            name: "diffuseTexture",
            kind: Texture(kind: Sampler2D, fallback: White),
            binding: 0
        ),
        (
            name: "fyrox_instanceData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 0
        ),
        (
            name: "fyrox_cameraData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 1
        ),
    ],

    disabled_passes: ["GBuffer", "DirectionalShadow", "PointShadow", "SpotShadow"],

    passes: [
        (
            name: "Forward",
            draw_parameters: DrawParameters(
                cull_face: None,
                color_write: ColorMask(
                    red: true,
                    green: true,
                    blue: true,
                    alpha: true,
                ),
                depth_write: false,
                stencil_test: None,
                depth_test: Some(Less),
                blend: Some(BlendParameters(
                    func: BlendFunc(
                        sfactor: SrcAlpha,
                        dfactor: OneMinusSrcAlpha,
                        alpha_sfactor: SrcAlpha,
                        alpha_dfactor: OneMinusSrcAlpha,
                    ),
                    equation: BlendEquation(
                        rgb: Add,
                        alpha: Add
                    )
                )),
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Keep,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),
            vertex_shader:
               r#"
                struct VertexInput {
                    @location(0) vertexPosition: vec3f,
                    @location(1) vertexTexCoord: vec2f,
                    @location(2) vertexParams: vec4f,
                    @location(3) vertexColor: vec4f,
                };

                struct VertexOutput {
                    @builtin(position) position: vec4f,
                    @location(0) texCoord: vec2f,
                    @location(1) color: vec4f,
                };

                @vertex fn vs_main(input: VertexInput) -> VertexOutput {
                    var output: VertexOutput;
                    let size = input.vertexParams.x;
                    let rotation = input.vertexParams.y;
                    let dx = input.vertexParams.z;
                    let dy = input.vertexParams.w;

                    output.texCoord = input.vertexTexCoord;
                    output.color = input.vertexColor;
                    let vertexOffset = S_RotateVec2(vec2f(dx, dy), rotation);
                    let worldPosition = fyrox_instanceData.worldMatrix * vec4f(input.vertexPosition, 1.0);
                    let offset = (vertexOffset.x * fyrox_cameraData.sideVector + vertexOffset.y * fyrox_cameraData.upVector) * size;
                    output.position = fyrox_cameraData.viewProjectionMatrix * (worldPosition + vec4f(offset.x, offset.y, offset.z, 0.0));
                    return output;
                }
               "#,

           fragment_shader:
               r#"
                @fragment fn fs_main(@location(0) texCoord: vec2f, @location(1) color: vec4f) -> @location(0) vec4f {
                    return color * S_SRGBToLinear(textureSample(diffuseTexture_tex, diffuseTexture_samp, texCoord));
                }
               "#,
        )
    ],
)
