(
    name: "StandardParticleSystemShader",

    resources: [
        (
            name: "diffuseTexture",
            kind: Texture(kind: Sampler2D, fallback: White),
            binding: 0
        ),
        (
            name: "fyrox_sceneDepth",
            kind: Texture(kind: DepthSampler2D, fallback: White),
            binding: 1
        ),
        (
            name: "properties",
            kind: PropertyGroup([
                (
                    name: "softBoundarySharpnessFactor",
                    kind: Float(value: 100.0),
                ),
                (
                    name: "useLighting",
                    kind: Bool(value: false),
                ),
            ]),
            binding: 0
        ),
        (
            name: "fyrox_instanceData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 1
        ),
        (
            name: "fyrox_cameraData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 2
        ),
        (
            name: "fyrox_lightsBlock",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 3
        ),
        (
            name: "fyrox_lightData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 4
        ),
    ],

    disabled_passes: ["GBuffer", "DirectionalShadow", "PointShadow", "SpotShadow"],

    passes: [
        (
            name: "Forward",
            draw_parameters: DrawParameters(
                cull_face: None,
                color_write: ColorMask(
                    red: true,
                    green: true,
                    blue: true,
                    alpha: true,
                ),
                depth_write: false,
                stencil_test: None,
                depth_test: Some(Less),
                blend: Some(BlendParameters(
                    func: BlendFunc(
                        sfactor: SrcAlpha,
                        dfactor: OneMinusSrcAlpha,
                        alpha_sfactor: SrcAlpha,
                        alpha_dfactor: OneMinusSrcAlpha,
                    ),
                    equation: BlendEquation(
                        rgb: Add,
                        alpha: Add
                    )
                )),
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Keep,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),
            vertex_shader:
               r#"
                struct VertexInput {
                    @location(0) vertexPosition: vec3f,
                    @location(1) vertexTexCoord: vec2f,
                    @location(2) particleSize: f32,
                    @location(3) particleRotation: f32,
                    @location(4) vertexColor: vec4f,
                };

                struct VertexOutput {
                    @builtin(position) position: vec4f,
                    @location(0) texCoord: vec2f,
                    @location(1) color: vec4f,
                    @location(2) fragmentPosition: vec3f,
                };

                @vertex fn vs_main(input: VertexInput) -> VertexOutput {
                    var output: VertexOutput;
                    output.color = S_SRGBToLinear(input.vertexColor);
                    output.texCoord = input.vertexTexCoord;
                    let vertexOffset = S_RotateVec2(input.vertexTexCoord * 2.0 - 1.0, input.particleRotation);
                    let worldPosition = fyrox_instanceData.worldMatrix * vec4f(input.vertexPosition, 1.0);
                    let offset = (vertexOffset.x * fyrox_cameraData.sideVector + vertexOffset.y * fyrox_cameraData.upVector) * input.particleSize;
                    let finalPosition = worldPosition + vec4f(offset.x, offset.y, offset.z, 0.0);
                    output.fragmentPosition = finalPosition.xyz;
                    output.position = fyrox_cameraData.viewProjectionMatrix * finalPosition;
                    return output;
                }
               "#,

           fragment_shader:
               r#"
                fn toProjSpace(z: f32) -> f32 {
                    return (fyrox_cameraData.zFar * fyrox_cameraData.zNear) / (fyrox_cameraData.zFar - z * fyrox_cameraData.zRange);
                }

                @fragment fn fs_main(
                    @location(0) texCoord: vec2f,
                    @location(1) color: vec4f,
                    @location(2) fragmentPosition: vec3f,
                    @builtin(position) fragCoord: vec4f
                ) -> @location(0) vec4f {
                    let depthTextureSize = textureDimensions(fyrox_sceneDepth_tex, 0);
                    let pixelSize = vec2f(1.0 / f32(depthTextureSize.x), 1.0 / f32(depthTextureSize.y));
                    let sceneDepth = toProjSpace(textureSample(fyrox_sceneDepth_tex, fyrox_sceneDepth_samp, fragCoord.xy * pixelSize));
                    let fragmentDepth = toProjSpace(fragCoord.z);
                    let depthOpacity = smoothstep((sceneDepth - fragmentDepth) * properties.softBoundarySharpnessFactor, 0.0, 1.0);

                    var lighting: vec3f;
                    if (properties.useLighting != 0u) {
                        lighting = fyrox_lightData.ambientLightColor.xyz;
                        for (var i: i32 = 0; i < min(i32(fyrox_lightsBlock.lightCount), 16); i++) {
                            let halfHotspotAngleCos = fyrox_lightsBlock.lightsParameters[i].x;
                            let halfConeAngleCos = fyrox_lightsBlock.lightsParameters[i].y;
                            let lightColor = fyrox_lightsBlock.lightsColorRadius[i].xyz;
                            let radius = fyrox_lightsBlock.lightsColorRadius[i].w;
                            let lightPosition = fyrox_lightsBlock.lightsPosition[i];
                            let direction = fyrox_lightsBlock.lightsDirection[i];

                            let toFragment = fragmentPosition - lightPosition;
                            let dist = length(toFragment);
                            let toFragmentNormalized = toFragment / dist;
                            let distanceAttenuation = S_LightDistanceAttenuation(dist, radius);
                            let spotAngleCos = dot(toFragmentNormalized, direction);
                            let directionalAttenuation = smoothstep(halfConeAngleCos, halfHotspotAngleCos, spotAngleCos);
                            lighting += lightColor * (distanceAttenuation * directionalAttenuation);
                        }
                    } else {
                        lighting = vec3f(1.0);
                    }

                    var fragColor = vec4f(lighting, 1.0) * color * S_SRGBToLinear(textureSample(diffuseTexture_tex, diffuseTexture_samp, texCoord)).r;
                    fragColor.a *= depthOpacity;
                    return fragColor;
                }
               "#,
        )
    ],
)
