(
    name: "Standard2DShader",

    resources: [
        (
            name: "diffuseTexture",
            kind: Texture(kind: Sampler2D, fallback: White),
            binding: 0
        ),
        (
            name: "fyrox_instanceData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 0
        ),
        (
            name: "fyrox_lightData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 1
        ),
        (
            name: "fyrox_lightsBlock",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 2
        ),
    ],

    disabled_passes: ["GBuffer", "DirectionalShadow", "PointShadow", "SpotShadow"],

    passes: [
        (
            name: "Forward",
            draw_parameters: DrawParameters(
                cull_face: None,
                color_write: ColorMask(
                    red: true,
                    green: true,
                    blue: true,
                    alpha: true,
                ),
                depth_write: true,
                stencil_test: None,
                depth_test: Some(LessOrEqual),
                blend: Some(BlendParameters(
                    func: BlendFunc(
                        sfactor: SrcAlpha,
                        dfactor: OneMinusSrcAlpha,
                        alpha_sfactor: SrcAlpha,
                        alpha_dfactor: OneMinusSrcAlpha,
                    ),
                    equation: BlendEquation(
                        rgb: Add,
                        alpha: Add
                    )
                )),
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Keep,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),
            vertex_shader:
               r#"
                struct VertexInput {
                    @location(0) vertexPosition: vec3f,
                    @location(1) vertexTexCoord: vec2f,
                    @location(2) vertexColor: vec4f,
                };

                struct VertexOutput {
                    @builtin(position) position: vec4f,
                    @location(0) texCoord: vec2f,
                    @location(1) color: vec4f,
                    @location(2) fragmentPosition: vec3f,
                };

                @vertex fn vs_main(input: VertexInput) -> VertexOutput {
                    var output: VertexOutput;
                    output.texCoord = input.vertexTexCoord;
                    output.fragmentPosition = (fyrox_instanceData.worldMatrix * vec4f(input.vertexPosition, 1.0)).xyz;
                    output.position = fyrox_instanceData.worldViewProjection * vec4f(input.vertexPosition, 1.0);
                    output.color = input.vertexColor;
                    return output;
                }
               "#,

           fragment_shader:
               r#"
                @fragment fn fs_main(
                    @location(0) texCoord: vec2f,
                    @location(1) color: vec4f,
                    @location(2) fragmentPosition: vec3f
                ) -> @location(0) vec4f {
                    var lighting = fyrox_lightData.ambientLightColor.xyz;
                    for (var i: i32 = 0; i < min(i32(fyrox_lightsBlock.lightCount), 16); i++) {
                        let halfHotspotAngleCos = fyrox_lightsBlock.lightsParameters[i].x;
                        let halfConeAngleCos = fyrox_lightsBlock.lightsParameters[i].y;
                        let lightColor = fyrox_lightsBlock.lightsColorRadius[i].xyz;
                        let radius = fyrox_lightsBlock.lightsColorRadius[i].w;
                        let lightPosition = fyrox_lightsBlock.lightsPosition[i];
                        let direction = fyrox_lightsBlock.lightsDirection[i];

                        let toFragment = fragmentPosition - lightPosition;
                        let distance = length(toFragment);
                        let toFragmentNormalized = toFragment / distance;
                        let distanceAttenuation = S_LightDistanceAttenuation(distance, radius);
                        let spotAngleCos = dot(toFragmentNormalized, direction);
                        let directionalAttenuation = smoothstep(halfConeAngleCos, halfHotspotAngleCos, spotAngleCos);
                        lighting += lightColor * (distanceAttenuation * directionalAttenuation);
                    }

                    return vec4f(lighting, 1.0) * color * S_SRGBToLinear(textureSample(diffuseTexture_tex, diffuseTexture_samp, texCoord));
                }
               "#,
        )
    ],
)
