(
    name: "Widget",
    resources: [
        (
            name: "fyrox_widgetTexture",
            kind: Texture(kind: Sampler2D, fallback: White),
            binding: 0
        ),
        (
            name: "fyrox_widgetData",
            kind: PropertyGroup([
                // Autogenerated
            ]),
            binding: 0
        ),
    ],
    disabled_passes: ["GBuffer", "DirectionalShadow", "PointShadow", "SpotShadow"],
    passes: [
        (
            name: "Forward",

            vertex_shader:
                r#"
                    struct VertexInput {
                        @location(0) vertexPosition: vec2f,
                        @location(1) vertexTexCoord: vec2f,
                        @location(2) vertexColor: vec4f,
                    };

                    struct VertexOutput {
                        @builtin(position) position: vec4f,
                        @location(0) texCoord: vec2f,
                        @location(1) color: vec4f,
                        @location(2) localPosition: vec2f,
                    };

                    @vertex fn vs_main(input: VertexInput) -> VertexOutput {
                        var output: VertexOutput;
                        output.texCoord = input.vertexTexCoord;
                        output.color = input.vertexColor;
                        output.localPosition = input.vertexPosition;

                        // Умножаем mat3x3 на vec3f (получаем vec3f)
                        let worldSpaceVertex = fyrox_widgetData.worldMatrix * vec3f(input.vertexPosition, 1.0);

                        // Умножаем mat4x4 на vec4f (получаем vec4f)
                        var clip_pos = fyrox_widgetData.projectionMatrix * vec4f(worldSpaceVertex, 1.0);

                        // WebGPU Z-range: конвертируем OpenGL [-1, 1] в WebGPU [0, 1]
                        clip_pos.z = (clip_pos.z + clip_pos.w) * 0.5;

                        output.position = clip_pos;
                        return output;
                    }
                "#,

            fragment_shader:
                r#"
                    fn project_point(a: vec2f, b: vec2f, p: vec2f) -> f32 {
                        let ab = b - a;
                        return clamp(dot(p - a, ab) / dot(ab, ab), 0.0, 1.0);
                    }

                    fn find_stop_index(t: f32) -> i32 {
                        var idx: i32 = 0;
                        for (var i: i32 = 0; i < i32(fyrox_widgetData.gradientPointCount); i++) {
                            if (t > fyrox_widgetData.gradientStops[i].x) {
                                idx = i;
                            }
                        }
                        return idx;
                    }

                    @fragment fn fs_main(
                        @location(0) texCoord: vec2f,
                        @location(1) color: vec4f,
                        @location(2) localPosition: vec2f
                    ) -> @location(0) vec4f {
                        let size = vec2f(fyrox_widgetData.boundsMax.x - fyrox_widgetData.boundsMin.x, fyrox_widgetData.boundsMax.y - fyrox_widgetData.boundsMin.y);
                        let normalizedPosition = (localPosition - fyrox_widgetData.boundsMin) / size;

                        var fragColor: vec4f;
                        if (fyrox_widgetData.brushType == 0) {
                            fragColor = fyrox_widgetData.solidColor;
                        } else {
                            var t: f32 = 0.0;
                            if (fyrox_widgetData.brushType == 1) {
                                t = project_point(fyrox_widgetData.gradientOrigin, fyrox_widgetData.gradientEnd, normalizedPosition);
                            } else if (fyrox_widgetData.brushType == 2) {
                                t = clamp(length(normalizedPosition - fyrox_widgetData.gradientOrigin), 0.0, 1.0);
                            }
                            let current = find_stop_index(t);
                            let next = min(current + 1, i32(fyrox_widgetData.gradientPointCount));
                            let delta = fyrox_widgetData.gradientStops[next] - fyrox_widgetData.gradientStops[current];
                            let mix_factor = (t - fyrox_widgetData.gradientStops[current]) / delta;
                            fragColor = mix(fyrox_widgetData.gradientColors[current], fyrox_widgetData.gradientColors[next], mix_factor);
                        }

                        let diffuseColor = textureSample(fyrox_widgetTexture_tex, fyrox_widgetTexture_samp, texCoord);

                        if (fyrox_widgetData.isFont != 0u) {
                            fragColor.a *= diffuseColor.r;
                        } else {
                            fragColor *= diffuseColor;
                        }

                        fragColor.a *= fyrox_widgetData.opacity;
                        fragColor *= color;
                        return fragColor;
                    }
                "#,
        ),
        (
            name: "Clip",

            draw_parameters: DrawParameters(
                cull_face: None,
                color_write: ColorMask(
                    red: false,
                    green: false,
                    blue: false,
                    alpha: false,
                ),
                depth_write: false,
                stencil_test: None,
                depth_test: None,
                blend: None,
                stencil_op: StencilOp(
                    fail: Keep,
                    zfail: Keep,
                    zpass: Incr,
                    write_mask: 0xFFFF_FFFF,
                ),
                scissor_box: None
            ),

            vertex_shader:
                r#"
                    @vertex fn vs_main(@location(0) vertexPosition: vec2f) -> @builtin(position) vec4f {
                        let worldSpaceVertex = fyrox_widgetData.worldMatrix * vec3f(vertexPosition, 1.0);
                        var clip_pos = fyrox_widgetData.projectionMatrix * vec4f(worldSpaceVertex, 1.0);
                        clip_pos.z = (clip_pos.z + clip_pos.w) * 0.5;
                        return clip_pos;
                    }
                "#,

            fragment_shader:
                r#"
                    @fragment fn fs_main() -> @location(0) vec4f {
                        return vec4f(1.0);
                    }
                "#,
        )
    ]
)
