// THEATRE-GLYPH: GlyphPreset — reusable visual/behavioral presets.
//
// A Glyph holds rendering code for one LayerType. Drop it onto a channel
// to replace that channel's active code. Glyphs load instantly from the
// Vault or are generated on-the-fly by an LLM (expect wait time).
//
// Progression: Glyph → Sigil (multi-channel) → Crest (sealed, identity-tagged Sigil)

use crate::layer::LayerType;
use myth_wire::MythId;
use serde::{Deserialize, Serialize};

/// Where this glyph's rendering code came from.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum GlyphSource {
    /// Loaded from the Vault by MythId. Instant — code is already stored.
    Vault(MythId),
    /// Generated on-the-fly by an LLM from a natural-language prompt.
    /// Expect wait time. `code` will be None until `fulfill()` is called.
    Llm { prompt: String },
    /// Hand-written or pasted directly into the session. No external dependency.
    Inline,
}

/// A reusable visual or behavioral preset that can be dropped onto a channel.
///
/// Glyphs are the atomic unit of the Theatre's creative vocabulary.
/// Each glyph targets exactly one LayerType — a GLSL glyph cannot go on a P5 channel.
///
/// When dropped onto a channel the channel's renderer switches to the glyph's code.
/// Saving a glyph writes it to myth-vault as a raw payload (bytes + MythId).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GlyphPreset {
    /// Unique identity for Vault storage and cross-session reference.
    pub id: MythId,
    pub name: String,
    /// The layer type this glyph targets.
    pub layer_type: LayerType,
    /// Where the code came from.
    pub source: GlyphSource,
    /// The rendering code. `None` while an LLM glyph is still generating.
    pub code: Option<String>,
    /// Free-form tags for Vault search and discovery.
    pub tags: Vec<String>,
    /// Unix timestamp (ms) of creation.
    pub created_at: i64,
}

impl GlyphPreset {
    /// Create a glyph from hand-written code. Ready immediately.
    pub fn new_inline(
        name: impl Into<String>,
        layer_type: LayerType,
        code: impl Into<String>,
    ) -> Self {
        Self {
            id: MythId::new(),
            name: name.into(),
            layer_type,
            source: GlyphSource::Inline,
            code: Some(code.into()),
            tags: Vec::new(),
            created_at: chrono::Utc::now().timestamp_millis(),
        }
    }

    /// Create a glyph stub that will be fulfilled from the Vault.
    /// `code` is None until `fulfill()` is called with the loaded bytes.
    pub fn new_from_vault(
        name: impl Into<String>,
        layer_type: LayerType,
        vault_id: MythId,
    ) -> Self {
        Self {
            id: MythId::new(),
            name: name.into(),
            layer_type,
            source: GlyphSource::Vault(vault_id),
            code: None,
            tags: Vec::new(),
            created_at: chrono::Utc::now().timestamp_millis(),
        }
    }

    /// Create a glyph that will be generated by an LLM.
    /// `code` is None until `fulfill()` is called with the generated output.
    pub fn new_llm(
        name: impl Into<String>,
        layer_type: LayerType,
        prompt: impl Into<String>,
    ) -> Self {
        Self {
            id: MythId::new(),
            name: name.into(),
            layer_type,
            source: GlyphSource::Llm {
                prompt: prompt.into(),
            },
            code: None,
            tags: Vec::new(),
            created_at: chrono::Utc::now().timestamp_millis(),
        }
    }

    /// Whether this glyph's code is ready to use.
    pub fn is_ready(&self) -> bool {
        self.code.is_some()
    }

    /// Whether this glyph is waiting on LLM generation or a Vault load.
    pub fn is_pending(&self) -> bool {
        self.code.is_none()
    }

    /// Fulfill a pending glyph with its generated or loaded code.
    /// Calling this on an already-ready glyph overwrites the existing code.
    pub fn fulfill(&mut self, code: impl Into<String>) {
        self.code = Some(code.into());
    }

    /// Add a tag for Vault search.
    pub fn tag(&mut self, tag: impl Into<String>) -> &mut Self {
        self.tags.push(tag.into());
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inline_glyph_is_immediately_ready() {
        let g = GlyphPreset::new_inline("static-noise", LayerType::Gl, "void main() {}");
        assert!(g.is_ready());
        assert!(!g.is_pending());
        assert_eq!(g.code.as_deref(), Some("void main() {}"));
    }

    #[test]
    fn llm_glyph_starts_pending() {
        let g = GlyphPreset::new_llm("despair-wash", LayerType::P5, "make it glitchy and dark");
        assert!(!g.is_ready());
        assert!(g.is_pending());
    }

    #[test]
    fn fulfill_makes_glyph_ready() {
        let mut g = GlyphPreset::new_llm("despair-wash", LayerType::P5, "make it glitchy");
        g.fulfill("function setup() { createCanvas(800, 540); }");
        assert!(g.is_ready());
        assert_eq!(g.layer_type, LayerType::P5);
    }

    #[test]
    fn vault_glyph_starts_pending() {
        let vault_id = MythId::new();
        let g = GlyphPreset::new_from_vault("saved-aurora", LayerType::Bv, vault_id);
        assert!(g.is_pending());
    }
}
