use crate::scene::{AtomKind, CanvasScene};

/// Generates a Rust source file containing a single `draw_<name>(ui: &mut Ui)` function
/// that reproduces every atom in the scene using egui painter calls.
pub fn to_rust(scene: &CanvasScene) -> String {
    let fn_name = scene.name.to_lowercase().replace(' ', "_");
    let mut out = String::new();

    out.push_str("// Auto-generated by myth-forge — do not edit by hand.\n");
    out.push_str("// Paste into your instrument module and call draw(ui) from update().\n\n");
    out.push_str("use egui::{Color32, Pos2, Rect, Rounding, Sense, Stroke, Ui, Vec2};\n\n");
    out.push_str(&format!("pub fn draw_{}(ui: &mut Ui) {{\n", fn_name));
    out.push_str("    let origin = ui.min_rect().min;\n\n");

    for atom in &scene.atoms {
        let [x, y] = atom.pos;
        let [w, h] = atom.size;
        let [r, g, b, a] = atom.params.color;
        let v = atom.params.value;
        let lbl = atom.params.label.replace('"', "\\\"");

        out.push_str(&format!(
            "    // {} — {}\n    {{\n",
            atom.kind.label(), lbl
        ));
        out.push_str(&format!(
            "        let rect = Rect::from_min_size(\n            origin + Vec2::new({:.1}, {:.1}),\n            Vec2::new({:.1}, {:.1}));\n",
            x, y, w, h
        ));
        out.push_str(&format!(
            "        let col = Color32::from_rgba_unmultiplied({}, {}, {}, {});\n",
            r, g, b, a
        ));

        match atom.kind {
            AtomKind::Knob => {
                out.push_str(&format!(
                    "        draw_knob(ui.painter(), rect, {:.3}, col, \"{}\");\n",
                    v, lbl
                ));
            }
            AtomKind::Fader => {
                out.push_str(&format!(
                    "        draw_fader(ui.painter(), rect, {:.3}, col);\n", v
                ));
            }
            AtomKind::Pad => {
                out.push_str(&format!(
                    "        draw_pad(ui.painter(), rect, {}, col, \"{}\");\n",
                    atom.params.lit, lbl
                ));
            }
            AtomKind::Jack => {
                out.push_str(&format!(
                    "        draw_jack(ui.painter(), rect, {}, col);\n",
                    atom.params.is_output
                ));
            }
            AtomKind::Meter => {
                out.push_str(&format!(
                    "        draw_meter(ui.painter(), rect, {:.3}, col);\n", v
                ));
            }
            AtomKind::Scope => {
                out.push_str("        draw_scope(ui.painter(), rect, tick);\n");
            }
            AtomKind::Label => {
                let text = atom.params.text.replace('"', "\\\"");
                out.push_str(&format!(
                    "        draw_label(ui.painter(), rect.left_center(), \"{}\");\n", text
                ));
            }
            AtomKind::Divider => {
                out.push_str("        draw_divider(ui.painter(), rect);\n");
            }
        }

        out.push_str("    }\n\n");
    }

    out.push_str("}\n");
    out
}
